name: Sync to GitLab

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.coinaxiom.xyz/github/yellowstone-grpc.git
          git push -f gitlab --all
          git push -f gitlab --tags
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
